name-template: '📦 $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
category-template: '#### $TITLE'
change-template: '- **#$NUMBER**: $TITLE - @$AUTHOR'
template: |
  $CHANGES
categories:
  - title: '🚨 Breaking'
    label: 'breaking'
  - title: '🔬Improvements'
    label: '💡 enhancement'
  - title: '🙌 New'
    label: 'feature'
  - title: '🩹 Bug fixes'
    label: '🐞 bug'
  - title: '⚙️ Maintenance'
    label: '⚙️ maintenance'
  - title: '📚 Documentation'
    label: '📚 docs'
  - title: '💾 Dependency Updates'
    label: 'dependencies'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - '💡 enhancement'
      - 'feature'
  patch:
    labels:
      - '🐞 bug'
      - '⚙️ maintenance'
      - '📚 docs'
      - 'dependencies'

exclude-labels:
  - 'skip-changelog'
