name: Release
on: 
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
        default: ""
        
jobs:
    bump_pod_version:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: setup fastlane
            run: brew install fastlane
          - name: bump version
            run: fastlane bump_version next_version:${{ github.event.inputs.release_version }}
    
    commit_changes:
      needs: bump_pod_version
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: commit changes
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            branch: 'develop'
            commit_message: 'Bump version ${{ github.event.inputs.release_version }}'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    create_release:
        runs-on: ubuntu-latest
        needs: commit_changes
        steps:
            - uses: actions/checkout@v2
            - name: publish release
              uses: release-drafter/release-drafter@v5
              with: 
                publish: true
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                 
    pod_trunk_push: 
        runs-on: macOS-latest
        needs: create_release
        steps:
          - uses: actions/checkout@v2
          - name: publish pod
            env:
              COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
            run: pod trunk push SkeletonView.podspec --allow-warnings --verbose
